apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: micro-secretstore
  namespace: micro
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/secrets.json
  - name: nestedSeparator
    value: "."